import { useCallback, useEffect, useState } from "react";
import { apiGetMember, apiSendMember, publicApiUrl } from "../lib/api";
import { formatGBPFromCents } from "../lib/formatGBP";

type Branding = {
  hasLogo: boolean;
  legalName: string | null;
  vatNumber: string | null;
  address: string | null;
  footerNote: string | null;
};

type InvoiceRow = {
  id: string;
  number: string | null;
  status: string | null;
  amountDue: number;
  amountPaid: number;
  total: number | null;
  currency: string;
  created: number;
  hostedInvoiceUrl: string | null;
  invoicePdf: string | null;
};

export function MemberBilling() {
  const [invoices, setInvoices] = useState<InvoiceRow[]>([]);
  const [stripeCustomerId, setStripeCustomerId] = useState<string | null>(null);
  const [branding, setBranding] = useState<Branding | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [portalLoading, setPortalLoading] = useState(false);

  const load = useCallback(() => {
    setLoading(true);
    setError(null);
    apiGetMember<{
      invoices: InvoiceRow[];
      stripeCustomerId: string | null;
      branding: Branding;
    }>("/api/member/portal/invoices")
      .then((d) => {
        setInvoices(d.invoices);
        setStripeCustomerId(d.stripeCustomerId);
        setBranding(d.branding);
      })
      .catch((e) => setError(e instanceof Error ? e.message : "Failed to load"))
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  const openPortal = async () => {
    setPortalLoading(true);
    setError(null);
    try {
      const { url } = await apiSendMember<{ url: string }>(
        "/api/member/portal/billing-portal",
        { method: "POST", body: "{}" }
      );
      window.location.href = url;
    } catch (e) {
      setError(e instanceof Error ? e.message : "Could not open portal");
      setPortalLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="p-8">
        <p className="text-slate-500">Loading billing…</p>
      </div>
    );
  }

  return (
    <div className="p-6 sm:p-8">
      <h1 className="font-display text-2xl font-semibold text-slate-900">
        Billing & invoices
      </h1>
      <p className="mt-2 max-w-xl text-sm text-slate-600">
        Invoices and receipts are generated by Stripe (PDFs and payment links).
        Use the button below to update cards, download PDFs, or manage
        subscriptions. Your operator can upload a logo in Staff → Integrations
        so it appears on Stripe invoices and emails.
      </p>

      {branding &&
      (branding.hasLogo ||
        branding.legalName ||
        branding.vatNumber ||
        branding.address ||
        branding.footerNote) ? (
        <div className="mt-6 flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-start">
          {branding.hasLogo ? (
            <img
              src={publicApiUrl("/api/public/branding/logo")}
              alt=""
              className="h-16 max-w-[180px] object-contain"
            />
          ) : null}
          <div className="min-w-0 text-sm text-slate-700">
            {branding.legalName ? (
              <p className="font-semibold text-slate-900">{branding.legalName}</p>
            ) : null}
            {branding.vatNumber ? (
              <p className="mt-1">VAT: {branding.vatNumber}</p>
            ) : null}
            {branding.address ? (
              <p className="mt-2 whitespace-pre-wrap text-slate-600">
                {branding.address}
              </p>
            ) : null}
            {branding.footerNote ? (
              <p className="mt-3 border-t border-slate-100 pt-3 text-xs text-slate-500">
                {branding.footerNote}
              </p>
            ) : null}
          </div>
        </div>
      ) : null}

      {error ? (
        <p className="mt-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">
          {error}
        </p>
      ) : null}

      <div className="mt-6 flex flex-wrap gap-3">
        <button
          type="button"
          onClick={() => void openPortal()}
          disabled={!stripeCustomerId || portalLoading}
          className="rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-brand-500 disabled:cursor-not-allowed disabled:opacity-50"
        >
          {portalLoading
            ? "Opening…"
            : "Manage payment methods & subscriptions"}
        </button>
        <button
          type="button"
          onClick={() => load()}
          className="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-medium text-slate-800 hover:bg-slate-50"
        >
          Refresh list
        </button>
      </div>

      {!stripeCustomerId ? (
        <p className="mt-6 text-sm text-slate-600">
          No Stripe billing profile is linked yet. After you pay for membership
          with a card, your invoices will appear here. If you were set up
          manually, contact Trader Watchdog for copies.
        </p>
      ) : null}

      {stripeCustomerId && invoices.length === 0 ? (
        <p className="mt-6 text-sm text-slate-600">
          No invoices yet. Future charges will show here and in your email from
          Stripe.
        </p>
      ) : null}

      {invoices.length > 0 ? (
        <div className="mt-8 overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm">
          <table className="w-full min-w-[640px] text-left text-sm">
            <thead className="border-b border-slate-200 bg-slate-50 text-xs uppercase text-slate-500">
              <tr>
                <th className="px-4 py-3">Date</th>
                <th className="px-4 py-3">Invoice</th>
                <th className="px-4 py-3">Status</th>
                <th className="px-4 py-3 text-right">Amount</th>
                <th className="px-4 py-3 text-right">PDF</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {invoices.map((inv) => {
                const cents =
                  inv.status === "paid"
                    ? inv.amountPaid
                    : inv.amountDue || inv.total || 0;
                const when = new Date(inv.created * 1000);
                return (
                  <tr key={inv.id}>
                    <td className="px-4 py-3 text-slate-700">
                      {when.toLocaleDateString("en-GB", {
                        day: "numeric",
                        month: "short",
                        year: "numeric",
                      })}
                    </td>
                    <td className="px-4 py-3 font-mono text-slate-800">
                      {inv.number ?? inv.id.slice(0, 12)}
                    </td>
                    <td className="px-4 py-3 capitalize text-slate-600">
                      {inv.status?.replace(/_/g, " ") ?? "—"}
                    </td>
                    <td className="px-4 py-3 text-right font-medium text-slate-900">
                      {formatGBPFromCents(cents)}
                    </td>
                    <td className="px-4 py-3 text-right">
                      {inv.hostedInvoiceUrl ? (
                        <a
                          href={inv.hostedInvoiceUrl}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="font-medium text-brand-600 hover:text-brand-500"
                        >
                          View
                        </a>
                      ) : inv.invoicePdf ? (
                        <a
                          href={inv.invoicePdf}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="font-medium text-brand-600 hover:text-brand-500"
                        >
                          PDF
                        </a>
                      ) : (
                        <span className="text-slate-400">—</span>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      ) : null}
    </div>
  );
}
